name: Update Lambda Layer and Function try 1

on:
  push:
    branches:
      - main

jobs:
  update-lambda-layer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Run Terraform
        run: |
          terraform init
          terraform apply -auto-approve ; terraform apply -lock=false
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }} #ap-southeast-1  # Replace with your desired AWS region
